apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: any-metric
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          args: {{ .Values.args | toJson }}
          ports:
            - containerPort: 8080
